apiVersion: 1

datasources:
  - name: vitald PostgreSQL
    orgId: 1
    uid: vitald-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: $VITALD_GRAFANA_DB_USER
    isDefault: true
    editable: false
    jsonData:
      database: $VITALD_GRAFANA_DB_NAME
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
      maxOpenConns: 4
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: $VITALD_GRAFANA_DB_PASSWORD
